---

#dependency:
#  name: galaxy
#  options:
#    role-file: recipes/test-devops-newfold/roles/requirements.yml

driver:
  name: docker

platforms:
  - name: role-python-version-test
    hostname: role-python-version-test.asouto.devops.test
    image: geerlingguy/docker-centos8-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    prebuild_image: true
provisioner:
  name: ansible
  env:
      MOLECULE_PYTHON_VERSION: ${MOLECULE_PYTHON_VERSION:-"3"}