---

- name: Install minikube
  get_url:
    url: "{{ minikube_binary_url }}"
    dest: "{{ minikube_binary_dest }}"
    mode: 755

- name: Systemd unit
  template: 
    src: "minikube.service.j2"
    dest: "/etc/systemd/system/minikube.service"
    mode: 0644
  
- name: Enable minikube service
  systemd:
    name: minikube
    state: started
    enabled: true
    daemon_reload: true
