---

driver:
  name: docker

platforms:
  - name: role-minikube-test
    hostname: role-minikube-test.asouto.devops.test
    image: molecule-almalinux9:latest
    pull: false
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    prebuild_image: true
